name: test-env
channels:
  - pytorch
  - conda-forge
  - ilastik-forge
  - defaults
dependencies:
  - lapack
  - black
  - mypy
  - python=3.7.*
  - paramiko=2.4.2
  - inferno=v0.3.3
  - pyzmq=18.0.1
  - pyyaml=3.13
  - pytest=4.3.0
  - pip:
    - typing-inspect==0.4.0
