# base config for robot
max_robo_iterations: 50
model_class_name: DUNet2D
model_init_kwargs: {in_channels: 1, out_channels: 14}
training: {
    training_shape: [1, 64, 64],
    batch_size: 8,
    loss_criterion_config: {"method": "MSELoss"},
    optimizer_config: {"method": "Adam"},
    num_iterations_done: 5,
}
validation: {}
dry_run: {"skip": False, "shrinkage": [0, 0, 0]}

model_dir: {
    path_to_folder: "/home/psharma/psharma/repos/tiktorch/tests/data/CREMI_DUNet_pretrained_new.zip",
    path_in_folder_to_model: "CREMI_DUNet_pretrained_new/model.py",
    path_in_folder_to_state: "CREMI_DUNet_pretrained_new/state.nn",
}

data_dir: {
    raw_data_base_folder: "/home/psharma/psharma/repos/tiktorch/tests/data/Hela_raw.h5",
    path_to_raw_data: "raw",
    labelled_data_base_folder: "/home/psharma/psharma/repos/tiktorch/tests/data/Hela_label.h5", 
    path_to_labelled: "labelled",
}

class_dict: {
    0: "background",
    1: "class1",
    2: "class2",
    3: "class3",
    4: "class4",
    5: "class5",
    6: "class6",
    7: "class7",
    8: "class8",
    9: "class9",
    10: "class10",
    11: "class11",
    12: "class12",
    13: "class13",
}

