# base config for robot
max_robo_iterations: 10
model_class_name: DUNet2D
model_init_kwargs: {in_channels: 1, out_channels: 1}
training: {
    training_shape: [1, 256, 256],
    batch_size: 1,
    loss_criterion_config: {"method": "NLLLoss", weight: [1.0, 1.0]},
    optimizer_config: {"method": "Adam", "lr": 1.0e-4},
    num_iterations_done: 0,
}
validation: {}
dry_run: {"skip": True, "shrinkage": [0, 0, 0]}

model_dir: {
    path_to_folder: "/home/psharma/psharma/repos/tiktorch/tests/data/CREMI_DUNet_pretrained_new.zip",
    path_in_folder_to_model: "CREMI_DUNet_pretrained_new/model.py",
    path_in_folder_to_state: "CREMI_DUNet_pretrained_new/state.nn",
}

data_dir: {
    raw_data_base_folder: "/home/psharma/psharma/repos/tiktorch/tests/data/Fluo_N2DH_train_raw.h5",
    path_to_raw_data: "raw",
    labelled_data_base_folder: "/home/psharma/psharma/repos/tiktorch/tests/data/Fluo_N2DH_train_label.h5", 
    path_to_labelled: "labelled",
    validation_raw_base: "/home/psharma/psharma/repos/tiktorch/tests/data/Fluo_N2DH_validation_raw.h5",
    validation_raw: "raw",
    validation_label_base: "/home/psharma/psharma/repos/tiktorch/tests/data/Fluo_N2DH_validation_label.h5",
    validation_label: "labelled"
}

strategy_params: {
    loss_fn: "BCELoss",
    class_dict: {
                    1: "background",
                    0: "cell"
                },

    labelling_strategy: "dense",
    annotation_percent: 0.6
}
